version = "1.0.0"
editor = ""
comment = ""
max_players = 6
default_locale = "zh-CN"

[[custom_actions]]
method = "top"
count = 2
[[custom_actions]]
method = "top"
count = 3
[[custom_actions]]
method = "top"
count = 7
